# Generated by Django 4.2.4 on 2023-08-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Muscles',
            new_name='Muscle',
        ),
    ]
