# Generated by Django 4.2.4 on 2023-08-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
