# Generated by Django 4.2.4 on 2023-08-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0002_remove_workout_image_workout_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='description',
            new_name='muscle_groups',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advice.workout')),
            ],
        ),
    ]
