# Generated by Django 4.2.4 on 2023-08-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0002_rename_muscles_muscle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('muscle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advice.muscle')),
            ],
        ),
    ]
