# Generated by Django 4.2.4 on 2023-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0003_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='muscle',
        ),
        migrations.AddField(
            model_name='exercises',
            name='muscle',
            field=models.ManyToManyField(to='advice.muscle'),
        ),
    ]
