# Generated by Django 4.2.4 on 2023-08-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_remove_exercise_group_workout_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advice.exercise'),
        ),
    ]
