# Generated by Django 4.2.4 on 2023-08-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0005_alter_workout_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advice.workout'),
        ),
    ]
