# Generated by Django 4.2.4 on 2023-08-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0005_alter_exercises_muscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
