# Generated by Django 4.2.4 on 2023-08-27 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0011_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='data',
            field=models.DateTimeField(default='2022-09-09', verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Фамилия'),
        ),
    ]
