# Generated by Django 4.2.4 on 2023-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0012_client_data_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
    ]
